<a href="https://colab.research.google.com/github/07gaura/ML-Learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**Basics**

---



In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[9,0,1],[2,3,4]])
print(b)

[[9 0 1]
 [2 3 4]]


In [ ]:
#get dimension
a.ndim

1

In [ ]:
# Get Shape
b.shape

(2, 3)

In [ ]:
#Get type
a.dtype

dtype('int64')

In [ ]:
#Get Size
a.itemsize

8

Accessing/Changing specific elements rows,columns,etc

---



In [ ]:
 a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
 print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specific element [r,c]
a[1,5]

13

In [ ]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific col
a[:,1]

array([2, 9])

In [ ]:
#lets deep dive [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

Initializing Different Types of Arrays

---



In [ ]:
#Three Dimensional zeroes matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#Three dimensional matrix with 1 value
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
#matrix with any number as float datatype
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#random decimal numbers
np.random.rand(4,2)

array([[0.02791593, 0.58416544],
       [0.6942699 , 0.14096613],
       [0.00674862, 0.89888432],
       [0.34259805, 0.53075021]])

In [ ]:
#Random integer values in b/w the range of 4 to 7
np.random.randint(4,7,size=(3,3))

array([[4, 6, 5],
       [6, 6, 6],
       [6, 4, 4]])

In [ ]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r2 = np.repeat(arr,3,axis=1)
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Mathematicss**
---



In [ ]:
 a = np.array([1,2,3,4])
 print(a)

[1 2 3 4]


In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a-2

array([-1,  0,  1,  2])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

**Statistics**

---





In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats,axis=0)

array([1, 2, 3])

In [ ]:
np.min(stats,axis=1)

array([1, 4])

Reorganizing Arrays

---



In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
#vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])